# Generated by Django 5.1.2 on 2024-10-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='mensaje',
            new_name='Informe',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Curso', 'En Curso'), ('Completada', 'Completada'), ('Archivar', 'Archivar')], default='Pendiente', max_length=20),
        ),
    ]
