# Generated by Django 5.1.2 on 2024-11-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informe',
            old_name='tipo_informe',
            new_name='categoría',
        ),
        migrations.AlterField(
            model_name='informe',
            name='imagen',
            field=models.ImageField(upload_to='informes/'),
        ),
        migrations.AlterField(
            model_name='reportetarea',
            name='imagen',
            field=models.ImageField(upload_to='reportes_tarea/'),
        ),
    ]
