# Generated by Django 5.1.2 on 2024-12-10 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_solicitudexterno_creado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestoexterno',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='presupuestoexterno',
            name='tarea_externo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto_externo', to='app.tareaexterno'),
            preserve_default=False,
        ),
    ]
