# Generated by Django 5.1.2 on 2024-10-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='tipo_Informe',
            field=models.CharField(choices=[('INF', 'Infraestructura'), ('MAQ', 'Maquinaria')], default='INF', max_length=3),
        ),
    ]
