# Generated by Django 5.1.2 on 2024-11-29 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_solicitudexterno'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(upload_to='presupuestos/')),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_asistencia', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.solicitudexterno')),
            ],
        ),
    ]
