# Generated by Django 5.1.2 on 2024-12-10 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_presupuestoexterno_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoexterno',
            name='tarea_externo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto_externo', to='app.tareaexterno'),
        ),
    ]
