# Generated by Django 5.1.2 on 2024-12-03 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_presupuestoexterno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudexterno',
            name='correo_externo',
        ),
        migrations.RemoveField(
            model_name='solicitudexterno',
            name='nombre_externo',
        ),
        migrations.AddField(
            model_name='solicitudexterno',
            name='externo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_externas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presupuestoexterno',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.solicitudexterno'),
        ),
    ]
