# Generated by Django 5.1.2 on 2024-12-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_archivo_pdf_presupuestoexterno_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoexterno',
            name='estado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
