# Generated by Django 5.1.2 on 2024-12-03 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_presupuestoexterno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoexterno',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='app.solicitudexterno'),
        ),
    ]
