# Generated by Django 5.1.2 on 2024-12-03 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_presupuestoexterno_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestoexterno',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presupuestoexterno',
            name='archivo',
            field=models.FileField(upload_to='ex_presupuestos/'),
        ),
        migrations.AlterField(
            model_name='presupuestoexterno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='presupuestoexterno',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto_externo', to='app.solicitudexterno'),
        ),
        migrations.AlterField(
            model_name='solicitudexterno',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ex_peticiones_imagenes/'),
        ),
        migrations.AlterField(
            model_name='solicitudexterno',
            name='pdf_peticion',
            field=models.FileField(blank=True, null=True, upload_to='ex_peticiones/'),
        ),
        migrations.CreateModel(
            name='TareaExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('en_espera', 'En Espera'), ('en_curso', 'En Curso'), ('completada', 'Completada')], default='en_espera', max_length=20)),
                ('fecha_asistencia', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_externas', to='app.solicitudexterno')),
            ],
        ),
        migrations.CreateModel(
            name='ExternoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ex_reporte_imagenes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea_externo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='app.tareaexterno')),
            ],
        ),
        migrations.CreateModel(
            name='ExternoFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField()),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea_externo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.tareaexterno')),
            ],
        ),
    ]
