# Generated by Django 5.1.2 on 2024-12-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_presupuestoexterno_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudexterno',
            name='objetivo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
