# Generated by Django 5.1.2 on 2024-12-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_solicitudexterno_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestoexterno',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tareaexterno',
            name='estado',
            field=models.CharField(choices=[('en_espera', 'En Espera'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='en_espera', max_length=20),
        ),
    ]
