# Generated by Django 5.1.2 on 2024-12-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_razon_rechazo_presupuestoexterno_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externofeedback',
            name='tarea_externo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='externo_feedback', to='app.tareaexterno'),
        ),
        migrations.AlterField(
            model_name='externoreporte',
            name='tarea_externo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='externo_reportes', to='app.tareaexterno'),
        ),
    ]
