from django.db.models.signals import post_migrate
from django.dispatch import receiver
from internal_workers.models import Zona, UbicacionTecnica, Equipo



@receiver(post_migrate)
def crear_datos_iniciales(sender, **kwargs):
    zonas_data = [
        ('Envase', 'ENV'),
        ('Bodega', 'BOD'),
        ('Fabrica', 'FAB'),
        ('Sistemas Criticos', 'CRI'),
        ('Inventario y Desarrollo', 'I&D')
    ]
    
    zonas_dict = {}

    for zona_nombre, zona_abrev in zonas_data:
        zona, created = Zona.objects.get_or_create(nombre=zona_nombre)
        zonas_dict[zona_abrev] = zona

    #crear Ubicaciones Tecnicas
    ubicaciones_tecnicas = {
    'BAGO-CL-PR-ENV-001-LINEA1' : 'Linea Marchesini 1',
    'BAGO-CL-PR-ENV-002-LINEA2' : 'Linea Marchesini 2',
    'BAGO-CL-PR-ENV-003-LINEA3' : 'Linea Romaco 1',
    'BAGO-CL-PR-ENV-004-LINEA4' : 'Linea Romaco 2',
    'BAGO-CL-PR-ENV-005-LINEA5' : 'Linea Maquina Comas',
    'BAGO-CL-PR-ENV-006-LINEA6' : 'Linea envasadora de cremas TGM',
    'BAGO-CL-PR-BOD-001-LINEA1' : 'Bodega Inflamables',
    'BAGO-CL-PR-BOD-002-LINEA2' : 'Sala Impresion Aluminio',
    'BAGO-CL-PR-BOD-003-LINEA3' : 'Equipos Camaras Bod. Santa Elena',
    'BAGO-CL-PR-FAB-001-LINEA1' : 'Linea Granulados',
    'BAGO-CL-PR-FAB-002-LINEA2' : 'Linea Compresion',
    'BAGO-CL-PR-FAB-003-LINEA3' : 'Linea recubrimiento',
    'BAGO-CL-PR-FAB-004-LINEA4' : 'Linea Liquidos',
    'BAGO-CL-PR-FAB-005-LINEA5' : 'Linea Cremas',
    'BAGO-CL-PR-CRI-001-PW'     : 'Equipos de Agua Purificada',
    'BAGO-CL-PR-CRI-002-DW'     : 'Equipos de Agua Potable',
    'BAGO-CL-PR-CRI-003-AirComp': 'Equipos de Aire Comprimido ',
    'BAGO-CL-PR-CRI-004-UMA'    : 'Equipos UMA',
    'BAGO-CL-PR-CRI-005-EQUIPOS': 'Eq. Auxiliares, Decantadores y Chillers',
    'BAGO-CL-PR-CRI-006-DIF'    : 'Metrologia Equipos Diferencial Presión',
    'BAGO-CL-PR-CRI-007-BAL'    : 'Metrología Equipos Balanzas',
    'BAGO-CL-PR-CRI-008-TEM'    : 'Metrología Equipos Temperatura',
    'BAGO-CL-PR-CRI-009-PRE'    : 'Metrologia Equipos Presión',
    'BAGO-CL-PR-CRI-010-VAC'    : 'Metrología Equipos Vacuometro',
    'BAGO-CL-PR-CRI-011-TIE'    : 'Metrología Equipos Tiempo',
    'BAGO-CL-PR-CRI-012-CON'    : 'Metrología Equipos Conductivimetro',
    'BAGO-CL-PR-CRI-013-PHM'    : 'Metrología Equipos Phmetros',
    'BAGO-CL-PR-CRI-014-AMP'    : 'Metrología Equipos Amperimetro',
    'BAGO-CL-PR-CRI-015-MET'    : 'Metrología Equipos Detectores de Metales',
    'BAGO-CL-PR-CRI-016-DES'    : 'Metrología Equipos Desintegrador',
    'BAGO-CL-PR-CRI-017-FRI'    : 'Metrologia Equipos Friabilómetro',
    'BAGO-CL-PR-CRI-018-MAS'    : 'Metrología Masas Patrones',
    'BAGO-CL-PR-CRI-019-TAC'    : 'Metrologia Equipos Tacometros',
    'BAGO-CL-PR-CRI-020-DIM'    : 'Metrología Equipos Dimensiones',
    'BAGO-CL-PR-CRI-021-DUR'    : 'Metrología Equipos Durometros',
    'BAGO-CL-PR-CRI-022-FUE'    : 'Metrología Equipos Celdas de Carga',
    'BAGO-CL-PR-CRI-023-ANE'    : 'Metrologia Equipos Anemómetro',
    'BAGO-CL-PR-CRI-024-CAU'    : 'Metrología Equipo BaLometro',
    'BAGO-CL-PR-CRI-025-MUT'    : 'Metrología Equipo Pinza Amperimetrica',
    'BAGO-CL-PR-CRI-026-TOR'    : 'Metrología Equipo Torquimetro',
    'BAGO-CL-PR-CRI-027-NIV'    : 'Metrología Sensor de Nivel',
    'BAGO-CL-PR-CRI-028-CTO'    : 'Metrologia Contador de Partículas',
    'BAGO-CL-PR-CRI-029-FAB'    : 'Metrología Cabinas de Flujo Laminar',
    'BAGO-CL-PR-CRI-030-CAL'    : 'Metrología Calibrador de Procesos',
    'BAGO-CL-PR-CRI-031-VIS'    : 'Metrologia Equipo Viscosímetro',
    'BAGO-CL-PR-CRI-032-TGHP'   : 'Metrología Sensores de Temperatura y Humedad',
    'BAGO-CL-PR-CRI-033-TGH'    : 'Metrologia Equipos Patrones de Temperatura y Humedad',
    'BAGO-CL-PR-I&D-001-LINEA1' : 'Linea Compresion',
    'BAGO-CL-PR-I&D-002-LINEA2' : 'Linea Granulados',
    'BAGO-CL-PR-I&D-003-LINEA3' : 'Linea Recubrimiento',
    'BAGO-CL-PR-I&D-004-LINEA4' : 'Linea Blistera',
    }

    # Datos de equipos
    equipos_por_ubicacion = {
        'BAGO-CL-PR-ENV-001-LINEA1': {
            'PR-ENV-31CL': 'Blistera Marchesini 1 MB 421',
            'PR-ENV-32CL': 'Estuchadora Marchesini 1 MA 305',
            'PR-ENV-33CL': 'Fajadora Marchesini 1 F 43',
        },
        'BAGO-CL-PR-ENV-002-LINEA2': {
            'PR-ENV-52CL': 'Blistera Marchesini 2 MB 422',
            'PR-ENV-53CL': 'Estuchadora Marchesini 2 MA 305',
        },
        'BAGO-CL-PR-ENV-003-LINEA3': {
            'PR-ENV-37CL': 'Blistera Romaco 1 NOACK N 921',
            'PR-ENV-38CL': 'Estuchadora Romaco 1 Promatic PC 300',
            'PR-ENV-39CL': 'Fajadora Romaco 1 CRIST',
        },
        'BAGO-CL-PR-ENV-004-LINEA4': {
            'PR-ENV-40CL': 'Blistera Romaco 2 DPN 760',
            'PR-ENV-06CL': 'Estuchadora Romaco 2 CAM AV 1',
        },
        'BAGO-CL-PR-ENV-005-LINEA5': {
            'PR-ENV-04CL': 'Llenadora de Frascos Comas',
            'PR-ENV-198CL': 'Aspiradora Kevac Comas',
            'PR-ENV-05CL': 'Etiquetadora Comas',
            'PR-ENV-30CL': 'Estuchadora CAM AV 2 Liquido',
        },
        'BAGO-CL-PR-ENV-006-LINEA6': {
            'PR-ENV-24CL': 'Envasadora de Cremas TGM',
            'PR-ENV-44CL': 'Estuchadora CAM AV3 crema',
            'PR-ENV-197CL': 'Aspiradora Ribo TGM',
        }, 
        'BAGO-CL-PR-BOD-001-LINEA1': {
            'PR-FAB-176CL':'Bomba Inflamable P100',
            'PR-FAB-35CL': 'Inflamable Mini Bomba',
            'PR-FAB-36CL': 'Inflamable Mini-M1',
        },
        'BAGO-CL-PR-BOD-002-LINEA2': {
            'PR-ENV-08CL':	'Impresora Aluminio Siat',
            'PR-ENV-42CL':	'Impresora Flexografia Flexo-Chile',
            'PR-ENV-51CL':	'Agitador Electrico',
        },
        'BAGO-CL-PR-BOD-003-LINEA3': {
            'PR-FAB-161CL':	'Camara Fresca',
            'PR-FAB-190CL':	'Camara Fria N°2',
        },
         'BAGO-CL-PR-FAB-001-LINEA1': {
            'PR-FAB-11CL': 'Secador Lecho Fluido Glatt',
            'PR-FAB-91CL': 'Rotogranulador SM-100',
            'PR-FAB-117CL': 'Mezclador en V240 Kg N°2',
            'PR-FAB-164CL': 'Elevador N°2',
            'PR-FAB-136CL': 'Secador de Lecho Fluido Cronimo',
            'PR-FAB-133CL': 'Rotogranulador Lodige',
            'PR-FAB-186CL': 'Mezclador en V240 Kg N°3',
            'PR-FAB-165CL': 'Elevador N°3',
            'PR-FAB-89CL': 'Mezclador en V 120 KG',
            'PR-FAB-90CL': 'Mezclador V 240 Kg N°1',
            'PR-FAB-163CL': 'Elevador N°1',
            'PR-FAB-118CL': 'Tamiz Ocilante MF-6-2 N°2',
            'PR-FAB-15CL': 'Tamiz Conico TC200',
            'PR-FAB-191CL': 'Agitador Electrico',
            'PR-FAB-131CL': 'Tamiz Osillowitt N°3',
            'PR-FAB-154CL': 'Tamiz Coniwitt 150 N°2',
            'PR-FAB-24CL': 'Agitador Neumatico N°1',
            'PR-FAB-88-CL': 'Tamiz Oscilante MF-6-1',
            'PR-FAB-150CL': 'Bomba Peristaltica',
            'PR-FAB-151CL': 'Bomba Peristaltica',
            'PR-FAB-126CL': 'Mezclador en V 10 KG',
            'PR-FAB-196-CL': 'Molino Tamiz Flexmillow',
            'PR-FAB-87CL': 'Mezclador en V 30 KG',
            'PR-FAB-116CL': 'Molino Martillo Multimill',
        },
        'BAGO-CL-PR-FAB-002-LINEA2': {
            'PR-FAB-169CL': 'Tabletera Kilian',
            'PR-FAB-106CL': 'Tabletera BB4',
            'PR-FAB-178CL': 'Tabletera Riva',
            'PR-FAB-19CL': 'Tabletera B3B',
            'PR-FAB-93CL': 'Tabletera Sejong',
            'PR-FAB-195CL': 'Tabletera Kilian N°2',
            'PR-FAB-177-CL': 'Detector de Metales',
            'PR-FAB-181CL': 'Desempolvador-Detector N°1',
            'PR-FAB-182CL': 'Desempolvador-Detector N°2',
            'PR-FAB-183CL': 'Desempolvador-Detector N°3',
            'PR-FAB-184CL': 'Desempolvador-Detector N°4',
            'PR-FAB-193CL': 'Desempolvador-Detector N°5',
        },
        'BAGO-CL-PR-FAB-003-LINEA3': {
            'PR-FAB-127CL': 'Paila 1 (120 KG)',
            'PR-FAB-128CL': 'Paila 2 (120 KG)',
            'PR-FAB-94CL': 'Paila 3 (94 KG)',
            'PR-FAB-137CL': 'Paila 4 (120 KG)',
            'PR-FAB-25CL': 'Agitador Electrico Lacas',
            'PR-FAB-39CL': 'Bomba Peristaltica N°1',
            'PR-FAB-156CL': 'Bomba Peristaltica N°5',
            'PR-FAB-157CL': 'Bomba Peristaltica N°6',
            'PR-FAB-172CL': 'Bomba Peristaltica N°7',
            'PR-FAB-187CL': 'Bomba Peristaltica N°8',
            'PR-FAB-31CL': 'Agitador Neumatico Paila 1',
            'PR-FAB-32CL': 'Agitador Neumatico Paila 2',
            'PR-FAB-33CL': 'Agitador Neumatico Paila 3',
            'PR-FAB-129CL': 'Agitador con Contenedor N°1',
            'PR-FAB-130CL': 'Agitador con Contenedor N°2',
            'PR-FAB-138CL': 'Agitador con Contenedor N°3',
            'PR-FAB-139CL': 'Agitador con Contenedor N°4',
        },
        'BAGO-CL-PR-FAB-004-LINEA4': {
            'PR-FAB-30CL': 'Agitador Neumatico',
            'PR-FAB-65CL': 'Reactor de 2000 L',
            'PR-FAB-95CL': 'Reactor de 500 L',
            'PR-FAB-34CL': 'Agitador electrico liquidos',
            'PR-FAB-96CL': 'Molino Coloidal Novinox',
            'PR-FAB-185CL': 'Bomba Glicerina',
            'PR-FAB-113CL': 'Bomba Sorbitol',
            'PR-FAB-100CL': 'Bomba Propilenglicol',
            'PR-FAB-26CL': 'Agitador Electrico',
            'PR-FAB111CL': 'Autoclave',
        },
        'BAGO-CL-PR-FAB-005-LINEA5': {
            'PR-FAB-63CL': 'Reactor N°1',
            'PR-FAB-62CL': 'Reactor N°2',
            'PR-FAB-57CL': 'Molino Coloideal Puc',
            'PR-FAB-29CL': 'Agitador Cremas',
            'PR-FAB-180CL': 'Bombas Fiti Air',
            'PR-FAB-155CL': 'Bomas Blagdom-Pump',
            'PR-FAB-99CL': 'Transportador de cremas',
        },
        'BAGO-CL-PR-CRI-001-PW': {
            'PR-CR-17CL': 'Bomba Sanitaria',
            'PR-CRI-15CL': 'Pulmón 1400 Lts',
            'PR-CRI-16CL': 'Filtro de Venteo #1',
            'PR-CRI-52CL': 'Lampara UV Loop Agua Purificada',
            'PR-CRI-26CL': 'Bomba P15 Presurización de linea',
            'PR-CRI-27CL': 'Bomba P17 de Concentrado',
            'PR-CRI-29CL': 'Filtro de Venteo Stilmas (Termocompresor M90)',
            'PR-CRI-46CL': 'Equipo UV Entrada de Agua Stilmas',
            'PR-CRI-18CL': 'Sistema Ablandador (Tambor sal, Dosificación Metabisulfito)',
            'PR-CRI-22CL': 'Bomba P60 Control Presion Ablandador',
            'PR-CRI-21CL': 'Bomba Elevación Presión Red Ablandador',
            'PR-CRI-47CL': 'Equipo UV Entrada de Agua Ablandador',
            'PR-CRI-20CL': 'Filtro 5 Micrones',
            'PR-CRI-19CL': 'Filtro Malla Lavable',
            'PR-CRI-23CL': 'Sistemas de Refrigeración (Sala de agua)',
            'PR-CRI-48CL': 'Equipo Osmosis Inversa 500 L/H',
            'PR-CRI-49CL': 'Bomba Distribucion agua de Osmosis',
            'PR-CRI-50CL': 'Bomba Recirculacion pulmón Osmosis',
            'PR-CRI-51CL': 'Lampara UV Recirculación Pulmon Osmosis',
        },
        'BAGO-CL-PR-CRI-002-DW': {
            'PR-CRI-13CL': 'Filtro de Arena',
            'PR-CRI-03CL': 'Depósito de Agua',
            'PR-CRI-08CL': 'Bomba de Elevación N°1',
            'PR-CRI-09CL': 'Bomba de Elevación N°2',
            'PR-CRI-04CL': 'Cilindros Hidroneumatico',
            'PR-CRI-05CL': 'Cilindros Hidroneumatico',
            'PR-CRI-06CL': 'Bomba Recirculacion N°1',
            'PR-CRI-07CL': 'Bomba Recirculacion N°2',
            'PR-CRI-10CL': 'Bomba de Achique',
            'PR-CRI-43CL': 'Clorador Dulcometer dialog',
            'PR-CRI-44CL': 'Bomba Dosificadora',
        },
        'BAGO-CL-PR-CRI-003-AirComp': {
            'PR-CRI-01CL': 'Compresor Atlas Copco',
            'PR-CRI-02CL': 'Compresor Kaeser CSD T SFC 105T',
        },
        'BAGO-CL-PR-CRI-004-UMA': {
            'PR-UMA-02CL': 'UMA Fabricación,Graneles,Envasado y Estuchado cremas',
            'PR-UMA-03CL': 'UMA Fab., Lavadero, Area comun y Graneles de Líquidos',
            'PR-UMA-05CL': 'UMA Envase 1er piso blistera Marchesini 1',
            'PR-UMA-06CL': 'UMA Área Granulados',
            'PR-UMA-07CL': 'UMA Sala Tabletera 2,3,4 ,Sala Paila 1,2,3',
            'PR-UMA-09CL': 'UMA Graneles Planta, Subterráneo y M. Primas',
            'PR-UMA-11CL': 'UMA Sala de Impresión de Aluminios',
            'PR-UMA-12CL': 'UMA Ingenieria y Mantencion',
            'PR-UMA-13CL': 'UMA Envase Blistera Romaco 2',
            'PR-UMA-21CL': 'UMA Inyección Pailas de Recubrimiento',
            'PR-UMA-23CL': 'UMA Sala Pesaje N°2',
            'PR-UMA-27CL': 'UMA Sala Fraccionamiento de Comprimidos',
            'PR-UMA-28CL': 'UMA Bodega M. Primas',
            'PR-UMA-29CL': 'UMA Sala de Pesaje N°1 y Utensilios Limpios',
            'PR-UMA-30CL': 'UMA Tabletera 5 y Tabletera 6',
            'PR-UMA-31CL': 'UMA Envase 2do Piso Oriente,Marchesini 2',
            'PR-UMA-32CL': 'UMA Envase 2do Piso, Blistera Romaco 1',
            'PR-UMA-33CL': 'UMA Llenado de Frascos (Comas)',
        },
        'BAGO-CL-PR-CRI-005-EQUIPOS': {
            'PR-FAB-51CL': 'Cabina de Flujo Laminar N°1',
            'PR-FAB-134CL': 'Cabina de Flujo Laminar N°2',
            'PR-CRI-37CL': 'Inyección Aux Aire Bodega de Inflamable',
            'PR-AUX-25CL': 'Extracción Aux Aire Bodega de Inflamable',
            'PR-CRI-36CL': 'Extracción Aux de Aire Exterior Glatt',
            'PR-CRI-35CL': 'Inyección de Aire Extractor Glatt',
            'PR-CRI-38CL': 'Inyeccion y Extraccion Aire Cronimo',
            'PR-CRI-45CL': 'Extracción Aux Tabletera 5 y 6',
            'PR-CRI-42CL': 'Extracción Aux Salas Granulados, recub.',
            'PR-AUX-29CL': 'Extracción de Aire Baños H. y M. Planta',
            'PR-CRI-31CL': 'Decantadores de polvos recubrimiento',
            'PR-CRI-30CL': 'Decantadores de Polvos Granulados Optiflo',
            'PR-CRI-32CL': 'Decantadores Polvos Recubrimiento (1-4)',
            'PR-CRI-33CL': 'Chillers Romaco I',
            'PR-CRI-34CL': 'Chillers Romaco 2',
            'PR-CRI-41CL': 'Chillers Cronimo',
        },
        'BAGO-CL-PR-CRI-006-DIF': {
            'PR-DIF-04CL': 'Exterior esclusa Materiales Romaco 1',
            'PR-DIF-05CL': 'Exterior esclusa Personas Romaco 1',
            'PR-DIF-06CL': 'Sala Blistera Romaco 1',
            'PR-DIF-07CL': 'Exterior esclusa Materiales Romaco 2',
            'PR-DIF-08CL': 'Exterior esclusa Personas Romaco 2',
            'PR-DIF-09CL': 'Sala Blistera Romaco 2',
            'PR-DIF-10CL': 'Sala exterior Tabletera N°5',
            'PR-DIF-11CL': 'Sala interior Tabletera N°5',
            'PR-DIF-12CL': 'Sala exterior Tabletera N°4',
            'PR-DIF-13CL': 'Sala interior Tabletera N°4',
            'PR-DIF-14CL': 'Sala exterior Tabletera N°2',
            'PR-DIF-15CL': 'Sala interior Tabletera N°2',
            'PR-DIF-16CL': 'Sala exterior Tabletera N°1',
            'PR-DIF-17CL': 'Sala interior Tabletera N°1',
            'PR-DIF-18CL': 'Exterior esclusa Paila 1-4',
            'PR-DIF-19CL': 'Interior Sala Paila 1-4',
            'PR-DIF-20CL': 'Exterior esclusa Paila 2',
            'PR-DIF-21CL': 'Interior Sala Paila 2',
            'PR-DIF-22CL': 'Exterior esclusa Paila 3',
            'PR-DIF-23CL': 'Interior Sala Paila 3',
            'PR-DIF-24CL': 'Sala exterior Tabletera N°6',
            'PR-DIF-25CL': 'Sala interior Tabletera N°6',
            'PR-DIF-26CL': 'Sala exterior Tabletera N°3',
            'PR-DIF-27CL': 'Sala interior Tabletera N°3',
            'PR-DIF-28CL': 'Sala Granulación 1 (Vía Húmeda 1)',
            'PR-DIF-29CL': 'Sala Granulación 2 (Vía Húmeda 2)',
            'PR-DIF-30CL': 'Sala Vía Seca (Mezclador 240kg N-1)',
            'PR-DIF-31CL': 'Sala Vía Seca (Mezclador 120kg N-2)',
            'PR-DIF-32CL': 'Sala Utensilios Limpios',
            'PR-DIF-33CL': 'Esclusa Materiales Granulado',
            'PR-DIF-34CL': 'Esclusa de Materiales Marchesini',
            'PR-DIF-35CL': 'Esclusa de Personas Marchesini',
            'PR-DIF-36CL': 'Sala Blistera Marchesini',
            'PR-DIF-37CL': 'Sala Llenadora de Líquidos',
            'PR-DIF-38CL': 'Exterior Esclusa Personas Llenadora',
            'PR-DIF-39CL': 'Interior Esclusa Personas Llenadora',
            'PR-DIF-40CL': 'Exterior Esclusa Materiales Llenadora',
            'PR-DIF-41CL': 'Interior Esclusa Materiales Llenadora',
            'PR-DIF-42CL': 'Sala Llenadora de Cremas/Linea Manual',
            'PR-DIF-43CL': 'Pasillo interior Fabricación Líquidos',
            'PR-DIF-44CL': 'Sala Difexon',
            'PR-DIF-45CL': 'Sala Reactores Líquidos',
            'PR-DIF-46CL': 'Sala Reactores Cremas',
            'PR-DIF-47CL': 'Sala Llenadora de Cremas/Pasillo Interior',
            'PR-DIF-48CL': 'Sala Llenadora de Cremas/Bodega Graneles Cremas',
            'PR-DIF-49CL': 'Exterior Sala Utensilios limpios',
            'PR-DIF-50CL': 'Exterior Esclusa personas Pesaje 1',
            'PR-DIF-51CL': 'Sala Pesaje 1',
            'PR-DIF-52CL': 'Exterior Esclusa Personas Pesaje 2',
            'PR-DIF-53CL': 'Sala Pesaje 2',
            'PR-DIF-54CL': 'Esclusa Materiales Sala Pesaje 2',
            'PR-DIF-55CL': 'Esclusa materiales fraccionamiento subterráneo',
            'PR-DIF-56CL': 'Esclusa personas fraccionamiento subterráneo',
            'PR-DIF-57CL': 'Sala Fraccionamiento Subterráneo',
            'PR-DIF-58CL': 'Esclusa materiales fraccio. entre sala y esclusa',
            'PR-DIF-59CL': 'Esclusa personas fraccionamiento subterráneo entre sala y esclusa',
            'PR-DIF-60CL': 'Interior esclusa material granel de envasado',
            'PR-DIF-61CL': 'Exterior esclusa material granel env.(pasillo)',
            'PR-DIF-62CL': 'Interior esclusa de personas Marchesini 2',
            'PR-DIF-63CL': 'Exterior esclusa de personas Marchesini 2',
        },
        'BAGO-CL-PR-CRI-009-PRE': {
            'PR-PRE-11CL': 'Manómetro Digital Dwyer',
            'PR-PRE-12CL': 'Manómetro Autoclave',
            'PR-PRE-13CL': 'Patrón Calibrador de Presión DRUCK',
            'PR-PRE-14CL': 'Manómetro Tabletera Sejong',
            'PR-PRE-15CL': 'Manómetro Tabletera Sejong',
            'PR-PRE-17CL': 'Manómetro Tabletera Sejong',
            'PR-PRE-18CL': 'Manómetro Tabletera Sejong',
            'PR-PRE-20CL': 'Manómetro Paila N°2',
            'PR-PRE-28CL': 'Manómetro Paila N°3',
            'PR-PRE-30CL': 'Manómetro Pistola Paila N°1',
            'PR-PRE-32CL': 'Manómetro Pistola Paila N°4',
            'PR-PRE-34CL': 'Interruptor de Presión Ablandador de Agua',
            'PR-PRE-35CL': 'Transmisor de Presión Ablandador de Agua',
            'PR-PRE-37CL': 'Transmisor de Presión Termocompresor STILMAS',
            'PR-PRE-38CL': 'Manómetro Termocompresor STILMAS',
            'PR-PRE-42CL': 'Transmisor de Presión Termocompresor STILMAS',
            'PR-PRE-43CL': 'Manómetro Dosificadora de Polvos (Presión Entrada)',
            'PR-PRE-44CL': 'Manómetro Dosificadora de Polvos (Cargador Polvo)',
            'PR-PRE-45CL': 'Manómetro Dosificadora de Polvos (Cargador Tapas)',
            'PR-PRE-46CL': 'Manometro Salida red de agua cisterna',
            'PR-PRE-47CL': 'Transmisor de Presión Salida red de agua cisterna',
            'PR-PRE-48CL': 'Transmisor de Presión Tabletera Sejong',
    },
        'BAGO-CL-PR-CRI-010-VAC': {
            'PR-VAC-05CL': 'Vacuómetro Línea Marchesini 2',
            'PR-VAC-07CL': 'Vacuómetro COMAS',
            'PR-VAC-09CL': 'Vacuómetro TGM',
            'PR-VAC-10CL': 'Vacuómetro Línea Romaco 1',
            'PR-VAC-11CL': 'Vacuómetro Blistera Romaco 2 (Salida de Blistera)',
            'PR-VAC-14CL': 'Vacuómetro Sala Línea Manual N°1',
            'PR-VAC-15CL': 'Vacuómetro Línea Manual N°1 (Subterráneo)',
            'PR-VAC-21CL': 'Vacuómetro Dosificadora de Polvos (Cargador Polvo)',
        },
        'BAGO-CL-PR-CRI-011-TIE': {
            'PR-TIE-03CL': 'Temporizador Reactor N°1 (Cremas)',
            'PR-TIE-04CL': 'Temporizador Reactor N° 2 (Cremas)',
            'PR-TIE-09CL': 'Temporizador Mezclador V 30 kg (Granulados)',
            'PR-TIE-15CL': 'Temporizador Mezclador V 240 kg #1 (Granulados)',
            'PR-TIE-16CL': 'Temporizador Mezclador V 240 kg #1 (Granulados)',
            'PR-TIE-18CL': 'Patrón Cronometro Casio',
            'PR-TIE-20CL': 'Temporizador Rotogranulador SM-100',
            'PR-TIE-21CL': 'Temporizador Mezclador V 240 kg #2 (Granulados)',
            'PR-TIE-22CL': 'Temporizador Mezclador V 10 kg',
            'PR-TIE-23CL': 'Temporizador Rotogranulador MGT-125P',
            'PR-TIE-24CL': 'Temporizador Mezclador V 120 kg #2 (Granulados Vía Seca)',
            'PR-TIE-25CL': 'Temporizador Mezclador V Pantalón (BETA)',
            'PR-TIE-26CL': 'Patrón Cronometro Casio',
        },
        'BAGO-CL-PR-CRI-012-CON': {
            'PR-CON-07CL': 'Conductivímetro Termocompresor STILMAS',
            'PR-CON-10CL': 'Conductivímetro Sala de Agua (Retorno de Línea)',
        },
        'BAGO-CL-PR-CRI-013-PHM': {
            'PR-PHM-01CL': 'PHmetro Liquidos, mesón',
            'PR-PHM-02CL': 'PHmetro Clorador Cisterna',
        },
        'BAGO-CL-PR-CRI-014-AMP': {
            'PR-AMP-03CL': 'Amperímetro Rotogranulador Sejong SM.100 (Granulados)',
            'PR-AMP-04CL': 'Amperimetro Rotogranulador Sejong SM.100 (Granulados)',
            'PR-AMP-07CL': 'Amperimetro Mezclador Rotogranulador MGT-125P (Granulados)',
            'PR-AMP-08CL': 'Amperimetro Chopper Rotogranulador MGT-125P (Granulados)',
        },
        'BAGO-CL-PR-CRI-015-MET': {
            'PR-MET-01CL': 'Detector de Metales CEIA',
            'PR-MET-02CL': 'Detector de Metales PRIMAS',
            'PR-MET-03CL': 'Detector de Metales CEIA',
            'PR-MET-04CL': 'Detector de Metales CEIA',
            'PR-MET-05CL': 'Detector de Metales CEIA',
            'PR-MET-06CL': 'Detector de Metales CEIA',
            'PR-MET-07CL': 'Detector de Metales CEIA',
            'PR-MET-08CL': 'Detector de Metales CEIA',
        },
        'BAGO-CL-PR-CRI-016-DES': {
            'PR-DES-02CL': 'Desintegrador Tester',
        },
        'BAGO-CL-PR-CRI-017-FRI': {
            'PR-FRI-03CL': 'Friabilómetro',
        },
        'BAGO-CL-PR-CRI-018-MAS': {
            'PR-MAS-01CL': 'Masa Patrón Set de masas (100g 500g 1kg)',
            'PR-MAS-02CL': 'Masa Patrón Set de masas (1, 2, 5, 10, 50, 100, 200, 500g  - 1 kg)',
            'PR-MAS-03CL': 'Masa Patrón 2 kg',
            'PR-MAS-05CL': 'Masa Patrón 20 kg',
            'PR-MAS-06CL': 'Masa Patrón 5 kg',
            'PR-MAS-07CL': 'Masa Patrón 20 kg',
            'PR-MAS-11CL': 'Masa Patrón Set de masas (1, 2, 5, 10, 50, 100, 200, 500g  - 1 kg)',
            'PR-MAS-15CL': 'Masa Patrón Set de patrones de masa de 1g a 500g',
            'PR-MAS-16CL': 'Masa Patrón 1kg',
            'PR-MAS-17CL': 'Masa Patrón 1kg',
            'PR-MAS-18CL': 'Masa Patrón 2kg',
            'PR-MAS-19CL': 'Masa Patrón 5kg',
            'PR-MAS-20CL': 'Masa Patrón 20kg',
            'PR-MAS-21CL': 'Masa Patrón 20kg',
            'PR-MAS-22CL': 'Masa Patrón 20kg',
            'PR-MAS-23CL': 'Masa Patrón 20kg',
            'PR-MAS-24CL': 'Masa Patrón 20kg',
            'PR-MAS-25CL': 'Masa Patrón 20kg',
            'PR-MAS-26CL': 'Masa Patrón 20kg',
            'PR-MAS-27CL': 'Masa Patrón 10kg',
            'PR-MAS-28CL': 'Masa Patrón 10 g',
            'PR-MAS-29CL': 'Masa Patrón 10 g',
            'PR-MAS-30CL': 'Masa Patrón 50 g',
            'PR-MAS-31CL': 'Masa Patrón 50 g',
            'PR-MAS-32CL': 'Masa Patrón 200 g',
            'PR-MAS-33CL': 'Masa Patrón 200 g',
            'PR-MAS-34CL': 'Masa Patrón 1kg',
            'PR-MAS-35CL': 'Masa Patrón 1 kg',
            'PR-MAS-36CL': 'Masa Patrón 10 kg',
            'PR-MAS-37CL': 'Masa Patrón 10 kg',
            'PR-MAS-38CL': 'Masa Patrón 20 kg',
            'PR-MAS-39CL': 'Masa Patrón kg',
        },
        'BAGO-CL-PR-CRI-019-TAC': {
            'PR-TAC-01CL': 'Tacómetro Bomba Watson MARLOW',
            'PR-TAC-05CL': 'Tacómetro Paila N° 2 (Recubrimiento)',
            'PR-TAC-06CL': 'Tacómetro Paila N° 3 (Recubrimiento)',
            'PR-TAC-10CL': 'Indicador de Velocidad Reactor 500 Lt (Fabricación Líquidos)',
            'PR-TAC-11CL': 'Indicador de Velocidad Reactor 2000 Lt (Fabricación Líquidos)',
            'PR-TAC-14CL': 'Tacómetro Tamiz cónico Frewitt',
            'PR-TAC-17CL': 'Tacómetro Agitador Rotogranulador SM-100',
            'PR-TAC-18CL': 'Tacómetro Molino multimill',
            'PR-TAC-19CL': 'Tacómetro Tamiz Oscilante Frewitt # 2',
            'PR-TAC-20CL': 'Tacómetro Tamiz Oscilante Frewitt # 3',
            'PR-TAC-22CL': 'Tacómetro TAMIZ CÓNICO FREWITT CONIWITT-150',
            'PR-TAC-24CL': 'Tacómetro Paila N° 1 (Recubrimiento)',
            'PR-TAC-25CL': 'Tacómetro Paila N° 4 (Recubrimiento)',
            'PR-TAC-26CL': 'Tacómetro Tamiz Oscilante Frewitt MF- 6 #1 (Granulación)',
            'PR-TAC-27CL': 'Tacómetro Bomba Peristáltica N° 7 (Recubrimiento)',
            'PR-TAC-28CL': 'Tacómetro Bomba Peristáltica N° 1 (Granulación)',
            'PR-TAC-29CL': 'Tacómetro Bomba Peristáltica N° 2 (Granulación)',
            'PR-TAC-30CL': 'Tacómetro Bomba Peristáltica N° 5 (Recubrimiento)',
            'PR-TAC-31CL': 'Tacómetro Bomba Peristáltica N° 6 (Recubrimiento)',
            'PR-TAC-35CL': 'Tacómetro Bomba Watson MARLOW',
            'PR-TAC-37CL': 'Tacómetro Chopper Rotogranulador SM-100',
            'PR-TAC-38CL': 'Patrón Tacómetro Láser Monarch Instrument',
            'PR-TAC-40CL': 'Tacómetro Molino Tamizador Oscillowitt-6, Crusher CC-6 CONIWITT-150',
            'PR-TAC-41CL': 'Tacómetro Bomba Peristáltica N° 9 (Recubrimiento)',
            'PR-TAC-42CL': 'Tacómetro Mezclador V- Fabricación Polvo',
            'PR-TAC-43CL': 'Tacómetro Mezclador V 10 Kg',
            'PR-TAC-44CL': 'Tacómetro Mezclador V 30 kg (Granulados)',
            'PR-TAC-45CL': 'Tacómetro Mezclador V 240 kg #3 (Granulados - Sala N° 2)',
            'PR-TAC-46CL': 'Tacómetro Mezclador V 240 kg #1 (Granulados - Vía seca)',
            'PR-TAC-47CL': 'Tacómetro Mezclador V 240 Kg # 2 (Granulados - Sala N° 1)',
            'PR-TAC-48CL': 'Tacómetro Mezclador V 120 Kg #1 (Granulados - Vía seca)',
        },
        'BAGO-CL-PR-CRI-020-DIM': {
            'PR-DIM-06CL': 'Dimensiones MULTICHECK II (Compresión)',
            'PR-DIM-07CL': 'Dimensiones MULTICHECK II (Compresión)',
            'PR-DIM-08CL': 'Dimensiones EASYCHECK (Compresión)',
            'PR-DIM-09CL': 'Dimensiones EASYCHECK (Compresión)',
            'PR-DIM-12CL': 'Dimensiones SOTAX',
            'PR-DIM-13CL': 'Dimensiones SOTAX',
        },
        'BAGO-CL-PR-CRI-021-DUR': {
            'PR-DUR-04CL': 'Durómetro MULTICHECK II (Compresión)',
            'PR-DUR-05CL': 'Durómetro EASYCHECK (Compresión)',
            'PR-DUR-07CL': 'Durómetro SOTAX',
        },
        'BAGO-CL-PR-CRI-022-FUE': {
            'PR-FUE-01CL': 'Celda de Carga Tabletera N° 1  Sejong GRC 18S',
            'PR-FUE-05CL': 'Celda de Carga Tabletera N°4 (MANESTY BB4)',
            'PR-FUE-06CL': 'Celda de Carga Tabletera MANESTY BB4',
            'PR-FUE-07CL': 'Calibrador de Celda de Carga Tabletera MANESTY BB4',
            'PR-FUE-08CL': 'Celda de Carga Tabletera MANESTY B3B',
            'PR-FUE-10CL': 'Celda de Carga Tabletera KILIAN  #1',
            'PR-FUE-11CL': 'Celda de Carga Tabletera RIVA',
            'PR-FUE-12CL': 'Celda de Carga Tabletera RIVA',
            'PR-FUE-14CL': 'Calibrador de celda de carga MLC-20K',
            'PR-FUE-15CL': 'Celda de Carga Tabletera KILIAN #2',
        },
        'BAGO-CL-PR-CRI-023-ANE': {
            'PR-ANE-01CL': 'Anemometro DWYER',
            'PR-ANE-03CL': 'Anemómetro VETO',
        },
        'BAGO-CL-PR-CRI-024-CAU': {
            'PR-CAU-01CL': 'Balómetro Digital',
        },
        'BAGO-CL-PR-CRI-025-MUT': {
            'PR-MUT-03CL': 'Pinza Amperimétrica Fluke 375',
            'PR-MUT-05CL': 'Pinza Amperimétrica Fluke 375',
            'PR-MUT-06CL': 'Patrón Pinza Amperimétrica Fluke 375fc',
        },
        'BAGO-CL-PR-CRI-026-TOR': {
            'PR-TOR-02CL': 'Torquimetro',
        },
        'BAGO-CL-PR-CRI-027-NIV': {
            'PR-NIV-05CL': 'Sensor de Nivel Estanque de agua purificada',
        },
        'BAGO-CL-PR-CRI-028-CTO': {
            'PR-CTO-02CL': 'Contador de Partículas HANDHELD HH3016',
            'PR-CTO-03CL': 'Contador de Partículas HANDHELD HH3017',
        },
        'BAGO-CL-PR-CRI-029-FAB': {
            'PR-FAB-51CL': 'Cabina de Flujo Laminar N°1',
            'PR-FAB-134CL': 'Cabina de Flujo Laminar N°2',
        },
        'BAGO-CL-PR-CRI-030-CAL': {
            'PR-CAL-01CL': 'Calibrador de Procesos Fluke 726',
        },
        'BAGO-CL-PR-CRI-031-VIS': {
            'PR-VIS-01CL': 'Viscosimetro Líquidos',
        },
        'BAGO-CL-PR-CRI-032-TGHP': {
            'PR-TGHP-01CL': 'Bodega Graneles y MPF   1° Nivel: Posición 4',
            'PR-TGHP-02CL': 'Bodega Graneles y MPF   2° Nivel: Posición 13',
            'PR-TGHP-03CL': 'Bodega Graneles y MPF   3° Nivel: Posición 23',
            'PR-TGHP-04CL': 'Bodega Graneles y MPF   4° Nivel: Posición 33',
            'PR-TGHP-05CL': 'Bodega Graneles y MPF   3° Nivel: Posición 27',
            'PR-TGHP-06CL': 'Bodega Graneles y MPF 4° Nivel: Posición 37',
            'PR-TGHP-07CL': 'Bodega Graneles y Materias Primas Fraccionadas',
            'PR-TGHP-08CL': 'Bodega Graneles y MPF   2° Nivel: Posición 15',
            'PR-TGHP-09CL': 'Bodega Graneles y MPF 4° Nivel: Posición 35',
            'PR-TGHP-10CL': 'Bodega Graneles y MPF   3° Nivel: Posición 20',
            'PR-TGHP-11CL': 'Bodega Graneles y MPF   4° Nivel: Posición 30',
            'PR-TGHP-12CL': 'Bodega Graneles y MPF 3° Nivel: Posición 24',
            'PR-TGHP-13CL': 'Bodega Graneles y MPF        1° Nivel: Posición 2',
            'PR-TGHP-14CL': 'Bodega Graneles y MPF        2° Nivel: Posición 11',
            'PR-TGHP-15CL': 'Central de Pesaje -   Sala N°1',
            'PR-TGHP-16CL': 'Central de Pesaje -   Sala N°2',
            'PR-TGHP-17CL': 'Vía Húmeda 1 (Granulados)',
            'PR-TGHP-18CL': 'Vía Húmeda 2 (Granulados)',
            'PR-TGHP-19CL': 'Vía Seca Mezclador 240k (Granulados)',
            'PR-TGHP-20CL': 'Vía Seca Mezclador 120k (Granulados)',
            'PR-TGHP-21CL': 'Tabletera N°1 (compresión)',
            'PR-TGHP-22CL': 'Tabletera N°2 (compresión)',
            'PR-TGHP-23CL': 'Tabletera N°3 (compresión)',
            'PR-TGHP-24CL': 'Tabletera N°4 (compresión)',
            'PR-TGHP-25CL': 'Tabletera N°5 (compresión)',
            'PR-TGHP-26CL': 'Tabletera N°6 (compresión)',
            'PR-TGHP-27CL': 'Recubrimiento N°1',
            'PR-TGHP-28CL': 'Recubrimiento N°2',
            'PR-TGHP-29CL': 'Recubrimiento N°3',
            'PR-TGHP-30CL': 'Sala Fraccionamiento (Subterráneo)',
            'PR-TGHP-31CL': 'Blistera Marchesini 1',
            'PR-TGHP-32CL': 'Llenadora Comas',
            'PR-TGHP-33CL': 'Reactores de Crema',
            'PR-TGHP-34CL': 'Envasado de Cremas TGM',
            'PR-TGHP-35CL': 'Reactores de líquido',
            'PR-TGHP-36CL': 'Blistera Romaco 1',
            'PR-TGHP-37CL': 'Blistera Romaco 2',
            'PR-TGHP-38CL': 'Blistera Marchesini 2',
            'PR-TGHP-39CL': 'Línea Manual N°1',
            'PR-TGHP-40CL': 'Pasillo Granulados',
            'PR-TGHP-41CL': 'Bodega de Líquidos',
            'PR-TGHP-42CL': 'Estuchado Piso 1',
            'PR-TGHP-43CL': 'Estuchado Piso 2',
            'PR-TGHP-44CL': 'Estuchado Marchesini 2',
            'PR-TGHP-45CL': 'Pasillo 1 Bodega Santa Elena',
            'PR-TGHP-46CL': 'Pasillo 2 Bodega Santa Elena',
            'PR-TGHP-47CL': 'Pasillo 3 Bodega Santa Elena',
            'PR-TGHP-48CL': 'Pasillo 4 Bodega Santa Elena',
            'PR-TGHP-49CL': 'Sala Difexon',
            'PR-TGHP-50CL': 'Graneles Crema',
            'PR-TGHP-51CL': 'Bodega Despacho',
            'PR-TGHP-52CL': 'Baño Mujeres',
            'PR-TGHP-53CL': 'Baño Hombres',
            'PR-TGHP-54CL': 'Bodega Folias',
            'PR-TGHP-55CL': 'Impresión de Aluminio',
            'PR-TGHP-56CL': 'Sala de Muestreo',
            'PR-TGHP-57CL': 'Bodega de Muestreo',
            'PR-TGHP-58CL': 'Pasillo Bodega de Muestreo',
        },
        'BAGO-CL-PR-CRI-033-TGH': {
            'PR-TGH-576CL': 'Medidor digital de Humedad y Temperatura Fluke 971',
            'PR-TGH-757CL': 'Medidor digital de Humedad y Temperatura Fluke 971',
            'PR-TGH-758CL': 'Medidor digital de Humedad y Temperatura Amprobe TH-3',
        },
        'BAGO-CL-PR-I&D-001-LINEA1': {
            'CC-ETC-03': 'Tabletera Riva Piccola 560',
        },
        'BAGO-CL-PR-I&D-002-LINEA2': {
            'CC-EMV-01': 'Mezclador V Pantalon',
            'CC-ELF-01': 'Secador de Lecho Diosna',
            'CC-ERG-01': 'Rotogranulador L&D',
            'CC-ERG-01': 'Rotogranulador SM-15',
        },
        'BAGO-CL-PR-I&D-003-LINEA3': {
            'CC-EPR-01': 'Paila de Recubrimiento L&D',
        },
        'BAGO-CL-PR-I&D-004-LINEA4': {
            'CC-EBL-01': 'Blistera Encapsulado BTM-88H',
        },
    }

    ubicaciones_a_crear = []
    equipos_a_crear = []

    for ubicacion, descripcion in ubicaciones_tecnicas.items():
        zona_abrev = ubicacion.split('-')[3]
        zona = zonas_dict.get(zona_abrev)
        if zona:
            if not UbicacionTecnica.objects.filter(codigo=ubicacion).exists():
                ubicacion_tecnica = UbicacionTecnica(
                    codigo=ubicacion,
                    zona=zona,
                    descripcion=descripcion
                )
                ubicaciones_a_crear.append(ubicacion_tecnica)

            equipos = equipos_por_ubicacion.get(ubicacion, {})
            for equipo_codigo, equipo_descripcion in equipos.items():
                if not Equipo.objects.filter(codigo=equipo_codigo).exists():
                    equipo_obj = Equipo(
                        codigo=equipo_codigo,
                        descripcion=equipo_descripcion,
                        ubicacion_tecnica=ubicacion_tecnica
                    )
                    equipos_a_crear.append(equipo_obj)

    if ubicaciones_a_crear:
        UbicacionTecnica.objects.bulk_create(ubicaciones_a_crear)
    if equipos_a_crear:
        Equipo.objects.bulk_create(equipos_a_crear)