# Generated by Django 5.1.2 on 2025-01-13 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('En Curso', 'En Curso'), ('Revision', 'Revision'), ('Archivada', 'Archivada')], default='En Curso', max_length=50)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignado_tarea', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ot', models.CharField(max_length=30, null=True)),
                ('solicitante', models.CharField(max_length=300, null=True)),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=50)),
                ('programado_para', models.DateField(max_length=50, null=True)),
                ('turno', models.CharField(choices=[('Dia', 'Dia'), ('Noche', 'Noche')], max_length=50)),
                ('descripcion_trabajo', models.TextField(max_length=100, null=True)),
                ('cod_equipo', models.CharField(max_length=50, null=True)),
                ('equipo', models.CharField(max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, default='No se han registrado observaciones', null=True)),
                ('realizado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignado_mantenimiento', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisado_por', to=settings.AUTH_USER_MODEL)),
                ('tarea_mantenimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informe_mantenimiento', to='mant_preventivo.tareamantenimiento')),
            ],
        ),
    ]
