# Generated by Django 5.1.2 on 2025-01-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mant_preventivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientopreventivo',
            name='tabla_dinamica',
            field=models.JSONField(default=list),
        ),
    ]
