# Generated by Django 5.1.2 on 2025-01-23 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mant_preventivo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientopreventivo',
            name='tabla_dinamica',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='descripcion_trabajo',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_tarea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='tipo_ot',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimientopreventivo',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignado_mantenimiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mantenimientopreventivo',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
