# Generated by Django 5.1.2 on 2025-01-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mant_preventivo', '0002_mantenimientopreventivo_tabla_dinamica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientopreventivo',
            name='descripcion_trabajo',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
