# Generated by Django 5.1.2 on 2025-01-22 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mant_preventivo', '0002_mantenimientopreventivo_tabla_dinamica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tareamantenimiento',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_tarea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mantenimientopreventivo',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignado_mantenimiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mantenimientopreventivo',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
