# Generated by Django 5.1.2 on 2025-01-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mant_preventivo', '0003_tareamantenimiento_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareamantenimiento',
            name='descripcion_trabajo',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='tipo_ot',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
