# Generated by Django 5.1.2 on 2025-01-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mant_preventivo', '0004_alter_mantenimientopreventivo_descripcion_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='descripcion_trabajo',
            field=models.TextField(null=True),
        ),
    ]
