# Generated by Django 5.1.2 on 2025-01-23 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='ex_peticiones_imagenes/')),
                ('pdf_peticion', models.FileField(upload_to='ex_peticiones/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('externo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_externas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TareaExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('en_espera', 'En Espera'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='en_espera', max_length=20)),
                ('fecha_asistencia', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_externas', to='external_workers.solicitudexterno')),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ex_presupuestos/')),
                ('fecha_asistencia', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('mensaje', models.TextField(null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea_externo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto_externo', to='external_workers.tareaexterno')),
            ],
        ),
        migrations.CreateModel(
            name='ExternoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(null=True)),
                ('imagen', models.ImageField(null=True, upload_to='ex_reporte_imagenes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea_externo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='externo_reportes', to='external_workers.tareaexterno')),
            ],
        ),
        migrations.CreateModel(
            name='ExternoFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField()),
                ('comentario', models.TextField(blank=True, default='Trabajo aprobado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea_externo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='externo_feedback', to='external_workers.tareaexterno')),
            ],
        ),
    ]
