# Generated by Django 5.1.2 on 2024-12-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externofeedback',
            name='comentario',
            field=models.TextField(blank=True, default='Trabajo aprobado'),
        ),
        migrations.AlterField(
            model_name='externoreporte',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='externoreporte',
            name='imagen',
            field=models.ImageField(null=True, upload_to='ex_reporte_imagenes/'),
        ),
        migrations.AlterField(
            model_name='presupuestoexterno',
            name='mensaje',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitudexterno',
            name='imagen',
            field=models.ImageField(upload_to='ex_peticiones_imagenes/'),
        ),
        migrations.AlterField(
            model_name='solicitudexterno',
            name='pdf_peticion',
            field=models.FileField(upload_to='ex_peticiones/'),
        ),
    ]
